### ISSUE TITLE
upstream this to buildroot?

### ISSUE THREAD

**Issue by pdp7** [damien-lemoal/riscv64-nommu-buildroot#6]
@damien-lemoal not sure if this is the best place to ask...
but someone asked me yesterday if buildroot support for k210 was going to get upstreamed into the buildroot project?

also, along those lines, is there a way for me to help?

**Comment by damien-lemoal** [comment]
@pdp7 Yes, we can definitely do that. Once 5.8.0 stable is released, the buildroot support should end up being mostly Kconfig and build config files modifications. So that should be easy to do.

**Comment by damien-lemoal** [comment]
This effort in on-going. Please see the buildroot mailing list and https://github.com/damien-lemoal/buildroot.
